### ISSUE TITLE
Access once

### ISSUE THREAD

**Issue by Arvendui** [ahivert/tgtg-python#104]
Is there a way in which I can access with the same credentials every time I run my script? (And not get the "We noticed you accessed from a new device" mail from too good to go every time?)

**Comment by ahivert** [comment]
For the moment, you will have to save the client and reuse it.
The solution would be to save only tokens and give it to the client but the client is not ready for that at the moment.
I will try to make this change this week.

**Comment by c-hloehuang** [comment]
Hi, has there been any update on this issue? I'm not able to figure out how to stop getting the new login emails

**Comment by christoschronopoulos** [comment]
+1 That would be good to know! Those emails are quite annoying :P
