### ISSUE TITLE
Sign Up isn't working

### ISSUE THREAD

**Issue by LeBastardV** [ahivert/tgtg-python#107]
When I try to signup with python I have this error: 
client = TgtgClient(email="test@test.com", password="password", name="name")
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by ahivert** [comment]
Oups sorry the readme is not correct. To sign up you have to use this method:

```
client = TgtgClient().signup_by_email(
        email="test@test.com", password="test@test.com", name="test"
    )
 ```
