### ISSUE TITLE
Does the API still work? TgtgLoginError

### ISSUE THREAD

**Issue by christoschronopoulos** [ahivert/tgtg-python#110]
Dear ahivert,

I am getting a TgtgLoginError when I try a script that used to work some months ago. I guess that TGTG decided to take action against those unofficial libraries and services. Fx. TGTG-Notifier is not working anymore. The following is the exact error I get. Is there any way to make it work? Am I doing something wrong? I look forward to receiving your reply!

`TgtgLoginError: (403, b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size="1px">\nRequest blocked.\nWe can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear="all">\n<HR noshade size="1px">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: c5ax6a80HaZW_vOW6HqWS_OR_dnWbMRpjZt0on1-FtuGu_ume3yVnQ==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>')`

**Comment by flippinger** [comment]
Can confirm, same error since a few days ago.

**Comment by MaxWinterstein** [comment]
This has already been discussed here, including workaround: https://github.com/ahivert/tgtg-python/issues/108

I provided some pull request that already was merged to master, but no new releases was published yet.

**Comment by ahivert** [comment]
New release available on pypi 0.6.0, thanks @MaxWinterstein
