### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by maartnjansn** [ahivert/tgtg-python#115]
It appears this method of requesting products is no longer working. A 403 error will occur when trying to connect.

**Comment by ahivert** [comment]
Can you try the new release 0.7.0 I just published?

**Comment by wieluk** [comment]
Hey I am also getting the 403 with the new release. I don't know how to get my access_token,
refresh_token and user_id without this client. 
```TgtgLoginError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMArI98rcWjSYcA2YrLzQ==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35693,\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')```

I am using version 0.7.0

**Comment by ahivert** [comment]
New release available 0.9.0
