### ISSUE TITLE
TgtgAPIError 401

### ISSUE THREAD

**Issue by christoschronopoulos** [ahivert/tgtg-python#117]
Dear all,

Since yesterday I have been receiving an error 401 when I call the client.get_items() function. 
`raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (401, b'{"timestamp":1635387434847,"status":401,"error":"Unauthorized","path":"/api/item/v7/"}')`
What can I do to solve it? Is it related to the API? Any help is very much appreciated!

**Comment by iMarkus** [comment]
In my case I needed to update the user agent to 21.9.3 to fix this

**Comment by christoschronopoulos** [comment]
> In my case I needed to update the user agent to 21.9.3 to fix this

Could you please elaborate more?? How can I update the user agent?

**Comment by iMarkus** [comment]
I am using node red to query the tgtg API based on this python sample and suddenly it stopped working. Then I had a look at this repository again and saw that the user agent has been updated. After that I also updated the user agent in node red and the 401 error was gone.

**Comment by MaxWinterstein** [comment]
@christoschronopoulos  which version are you running? This particular issue was fixed with `0.6.0`

**Comment by ahivert** [comment]
New version available, please use the 0.7.0

**Comment by ahivert** [comment]
new version available 0.9.0
