### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by TanguyOrtegat** [ahivert/tgtg-python#121]
Hello, 

I am already a user of tgtg bot but from anotehr repo. Unfortunatly it stopped working due to login changes. I was looking then for another repo that did the same and came to yourse. 
I installed everything correctly, but when launching to get my favorite items i am stuck with a 404 error on login. I've seen that everyone is getting 403 error but for me it is a 404. Did I something wrong or ? ...

![image](https://user-images.githubusercontent.com/17274032/142437868-4312bd28-b117-4949-99c0-b953142ef160.png)
![image](https://user-images.githubusercontent.com/17274032/142437909-e92d52a6-8e5b-4359-817b-c4e3205ce06f.png)

**Comment by matteoscrugli** [comment]
same issue

**Comment by goegol** [comment]
facing same issue with https://github.com/Chouffy/home_assistant_tgtg

**Comment by Dielee** [comment]
Mine is working fine for a few days...

**Comment by goegol** [comment]
@Dielee when you do the first setup before 32 hours ago, everything is fine...after that tgtg changed there api

**Comment by Dielee** [comment]
But 0.7.0 fixes the new api ?

**Comment by TanguyOrtegat** [comment]
yes, now when you want to login to tgtg, you enter email in the app, then tgtg sends you and email that you need to accept and then you are automaticly logged in to the app. no password needed anymore.

0.7.0 works with token if you have them, elseemail and password not

**Comment by Dielee** [comment]
Ah, thanks for this info! I will try to create an new tgtg account to test this :)

**Comment by TanguyOrtegat** [comment]
> Ah, thanks for this info! I will try to create an new tgtg account to test this :)

no need to create new account, just log off, and relog into the app and you'll see

**Comment by Dielee** [comment]
Yes, sure, but my bot is working now. I don't want to try this with my real acc.

**Comment by Chouffy** [comment]
> 0.7.0 works with token if you have them, else email and password not

I would add that this is since only few days. On 15 November I was able to connect with user/password and retrieve my tokens using 0.7.0 ... So now we need to retrieve the token in other means 🙃

**Comment by Dielee** [comment]
I have build a new version witch works with the new endpoints.
You have to use only Tgtgclient with an email:

`TgtgClient(email="dqweds@yourmail.de")`
`tgtgclient.login()`

After loging in, you should get an email.
Klick on this link and your good to go ;) 
PS: You have 2 Minutes to click this Link!

Changes are here:
https://github.com/Dielee/tgtg-python

**Comment by TanguyOrtegat** [comment]
> I have build a new version witch works with the new endpoints. You have to use only Tgtgclient with an email:
> 
> `TgtgClient(email="dqweds@yourmail.de")` `tgtgclient.login()`
> 
> After loging in, you should get an email. Klick on this link and your good to go ;) PS: You have 2 Minutes to click this Link!
> 
> Changes are here: https://github.com/Dielee/tgtg-python
> 
> Please give me feedback. If this works, I will open an PR.

looks like working ok, but gives an error with 200 status? 200 means ok? ...
![image](https://user-images.githubusercontent.com/17274032/142644622-a9c59a35-a324-403f-96b1-70ec1865267b.png)

**Comment by Dielee** [comment]
Fixed the wrong exception, but in the edit, there is someting wrong with your clone.
We are not using this endpoint anymore..

**Comment by TanguyOrtegat** [comment]
> ut in the edit, there is someting wrong with your clone

i'll retry. it's juste intellij taht is informing that variable doesn't exist and it is in your repo. 
https://github.com/Dielee/tgtg-python/blob/master/tgtg/__init__.py#L251
But please make so we can open issues on your repo to avoid discussing irelevant thing here about your repo and not the issue here discussed

**Comment by Dielee** [comment]
Thanks for this hint, issues are now open!

**Comment by TanguyOrtegat** [comment]
Your nez commit did the trick, it is working fine! congratz!
https://github.com/Dielee/tgtg-python/commit/a4bd08d4c2de3817617b1af07a3441d08f00918d

what you need to do in oprder to work just log in 1 time, retrieve tokens and login each time with those tokens, no need to activate by email

**Comment by xixov** [comment]
@Dielee thanks for providing a fix! I tested your code and I get a `KeyError: 'polling_id'` error once the login request comes back (line `polling_id = first_login_response["polling_id"]`). I checked `response.json` and it gave me only `{'state': 'TERMS'}`

**Comment by Dielee** [comment]
Please open up an issue at the forked repo!

**Comment by ahivert** [comment]
New release 0.8.0 should fix that, implemented by @Dielee

**Comment by ahivert** [comment]
If there is still an error with new release 0.9.0 please reopen the issue
