### ISSUE TITLE
Client doesn't print credentials

### ISSUE THREAD

**Issue by driesherman** [ahivert/tgtg-python#141]
Thank you very much for designing this piece of software! It's absolutely a great help.

I did notice one thing that bugged me. The readme states that after running the get_credentials() function, the client will print the needed tokens. This didn't work for me, so i took a quick look at the source code and saw that the function only returned the tokens, not print them.

Could you change this in the Readme please? This way, someone with less knowledge of python could still use the library and not get frustrated and give up their (maybe) first Python project. Thanks!

**Comment by ahivert** [comment]
thanks! updated :)
