### ISSUE TITLE
400 error on login

### ISSUE THREAD

**Issue by Immelstorn** [ahivert/tgtg-python#16]
Hi! I have some problems trying to login using email/pass. I am gettings 400 error with 
```
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner. 
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
```

Does it mean I somehow was banned by cloudfront? I tried different PCs with different IPs and user-agents and email/password pairs. Still the same.

**Comment by MaxWinterstein** [comment]
Currently works pretty fine for me.

But, i think i saw this problem a few days ago. Login was not possible for me via the iPhone app itself. After a few hours it was fine agian. Did you try to simply login from your phone?

**Comment by Immelstorn** [comment]
Yeah, it works from phone. Weird, I can't understand what parameter is banned - tried to change every of them

**Comment by MaxWinterstein** [comment]
mind sharing some code snipped? still working fine for me.
Some weird character inside your password?

**Comment by Immelstorn** [comment]
No weird characters and no tricky code, just 
`client = TgtgClient(email=email@email.com', password='password')`
but it seems to be resolved, I guess it was some request limiter by CloudFront. I have no problems anymore. Anyway, thanks for help attempts :)
