### ISSUE TITLE
tgtg-notifier.com redirects to fishy websites

### ISSUE THREAD

**Issue by nicolashohm** [ahivert/tgtg-python#164]
I noticed the URL tgtg-notifier.com redirects to some fishy websites. I don't know if the tgtg-notifier is related to this project. Maybe the link should be removed from this repo?

Apart from that: the lib works like a charm so far. Awesome job! I like the filter options possible with `get_items`.

**Comment by nicolashohm** [comment]
I just found a facebook post on their page, explaining that tgtg notfier has been shutdown: https://www.facebook.com/tgtgnotifier/

**Comment by ahivert** [comment]
thanks to remind me that! website removed
