### ISSUE TITLE
Dependency conflict for `requests` between Home Assistant and this module

### ISSUE THREAD

**Issue by Chouffy** [ahivert/tgtg-python#169]
Hi,

Thanks for this great piece of code. As you may know, I use it to power a Home Assistant integration ([here](https://github.com/Chouffy/home_assistant_tgtg).

One thing bothering me are dependency conflicts. Both Home Assistant and tgtg-python fixes their `requests` dependencies - [here for HA](https://github.com/home-assistant/core/blob/dev/requirements.txt#L21)

Today the situation is as follow:
* Home Assistant Production users needs to use `tgtg` 0.11.3 as HA require requests==2.27.1
* Home Assistant Development users needs to use `tgtg` 0.11.4 as HA require requests==2.28.0

Could we lighten the `tgtg` requirement to a non-fixed `requests` dependency?
What is the best way the Python community handle that?

Thanks for your help :)

**Comment by ahivert** [comment]
Hi,

That's what I've done in the last release with ^2.28.0
I think it could work if we replace this by ^2.27.1

Will you be able to try it if I provide you a branch with this change
without publishing it to pypi?

After that I would publish a new version with this validated change.

**Comment by Chouffy** [comment]
Hey @ahivert,
I'm up for it, let's try! 
I'll install this branch in both HA production and HA dev. If it works then it will be great!

**Comment by ahivert** [comment]
branch is ready, the name is `requests-2.27.1+`

I've opened a PR => https://github.com/ahivert/tgtg-python/pull/170 

If it's ok on your side I will merge it and publish it on pypi 🤞

**Comment by Chouffy** [comment]
Nice, thanks!
I was able to test with Home Assistant Dev, which has the most restrictive requirement (`requests==2.28.0`) and it worked like a charm.
However, I wasn't able to test on Home Assistant Prod as I don't know how to install manually the `tgtg` module. But I'm confident that it'll work, as it's the same `requests` requirements.

So if that's good for you, I'm up for publishing and I'll update the integration on my end!

**Comment by ahivert** [comment]
0.12.0 available on Pypi let me know 😉

**Comment by Chouffy** [comment]
Awesome, it works like a charm!
I've published the [associated release](https://github.com/Chouffy/home_assistant_tgtg/releases/tag/4.2.0).

Thanks for your help :)
