### ISSUE TITLE
How to get the time a store sold out?

### ISSUE THREAD

**Issue by bee395** [ahivert/tgtg-python#179]
Does the library also provide the functionality to get the time when a store is sold out? Like "sold out since yesterday 20:00"
I tried to find it in the response of `get_item`, but wasn't able to find anything like it

**Comment by MaxWinterstein** [comment]
Is pretty easy accessible:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/5927148/184529984-07cab498-d93b-4991-8c27-5ab22ccb061c.png">

https://github.com/ahivert/tgtg-python/blob/5f7d7fc1103f0439cbeb488168bca9b33e06241f/tests/constants.py#L9

**Comment by bee395** [comment]
I see, it's on shop instead of item level. Thanks for your help!

**Comment by MaxWinterstein** [comment]
> I see, it's on shop instead of item level. Thanks for your help!

yeah, kinda confusing. But I guess this is more designed from an app view of usage, not how a good data structure should be 😉

**Comment by bee395** [comment]
Looks like it's on the highest level, so not on item or store
"sold_out_at" is also hidden when items are still available or when recently no items were made available

`[{
   "item":{ },
   "store":{ },
   ...
   "sold_out_at":"2022-08-13T20:42:22Z",
   ...
}]`
