### ISSUE TITLE
Cant connect to client anymore

### ISSUE THREAD

**Issue by nickhir** [ahivert/tgtg-python#183]
Hello,

just quickly wanted to ask if anyone else is having trouble connecting to the client?

This is how I usually do it: 

```python
#################
# run this only once #
#################
# from tgtg import TgtgClient
#
# client = TgtgClient(email="nick.hirschmueller@yahoo.de")
# credentials = client.get_credentials()
#
# # go to email and verify
# import json
# # save credentials to disk
# with open("/home/pi/projects/tgtg_access/credentials.json", "w") as f:
#     json.dump(credentials, f, indent=4)
#

with open("/home/pi/projects/tgtg_access/credentials.json", "r") as f:
    credentials = json.load(f)

client = TgtgClient(access_token=credentials["access_token"],
                    refresh_token=credentials["refresh_token"],
                    user_id=credentials["user_id"])
print("Connected to client")
```

For some reason, it just never connects... I have used the same code for the last months and never had an issue. Do my credentials expire after a certain time? 

Any help is much appreciated.

**Comment by nickhir** [comment]
Correction:
It just takes very long to connect. 
And prints the following message: 
Failed to get last version
Using version 22.5.5

**Comment by ahivert** [comment]
Are you using the last tgtg-python version available on pypi? A New version
has been published this week to fix this error.

**Comment by christoschronopoulos** [comment]
I installed the latest version from pypi earlier today and I confirm that it works fine!
