### ISSUE TITLE
Notifications push de panier ajouter dans les favoris 

### ISSUE THREAD

**Issue by karasFR79** [ahivert/tgtg-python#220]
Bonjour est il possible de prévoir une fonction permettant d'avoir une notification immédiate lors de mise à disposition d'un nouveau panier ? (Dans nos favoris par exemple) 
Et dans l'idéal est il possible d'ajouter un ou plusieurs de ces paniers de manière automatique afin de les régler lors de la réception de la notification ?

Merci 🙏👌

**Comment by axoroll7** [comment]
In english ?
You need to create a loop with a timer, and ask the API the number of available "paniers".

**Comment by LauPaSat-pl** [comment]
You can check out my script. It checks for available packs from your favorites and sends a Telegram message if it's available. 
[Here](https://github.com/LauPaSat-pl/TGTG_notifications)
