### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by jakmanne** [ahivert/tgtg-python#223]
Would it be possible to use the refresh token to get a new access token? With the current setup I have to manually go to my email to confirm the login everytime, but is it possible to only do this one time, and then let the refresh token get a new access token?

**Comment by Ed-Infrared** [comment]
After you initial login wich you have confirmed in you email, you get the tokens but also a cookie. When you store the cookie and use it the next time you don't have to confirm with email.

`
tgtg_client = TgtgClient(access_token="<your token>, 
                                           refresh_token= <your token>, 
                                           user_id=<your id>, 
                                           cookie=<your cookie>)
`

**Comment by jakmanne** [comment]
Thanks for reply @Ed-Infrared . Does this mean that the TgTgClient will be granted access indefinitely? Or does it require to once in a while to re-authenticate with the email ?

Great job with the project!

**Comment by Ed-Infrared** [comment]
I am just another user of this great library. I am using this for 2 weeks and didn't have to renew my login  yet even between reboots.
