### ISSUE TITLE
Radius argument for "get_items" seems to have a limit

### ISSUE THREAD

**Issue by beauthi** [ahivert/tgtg-python#227]
I have a list of favorite bags which are all located in my city, close to the longitude and latitude I've set in my script.
When calling `get_items()` with `favorites_only=True`, it works correctly. However, when calling `get_items()` with `favorites_only=False`, there's about 3 of my favorites that show up. I've tried changing the value of the `radius` argument to really high numbers but it appears that there's a limit.
Do you know if there's a limit with radius argument? While using the app, there are way more stores that show up than when I use `get_items` with a high radius so this behaviour looks abnormal.

**Comment by pchr8** [comment]
We solved a similar issue by making the radii smaller but multiple, thereby covering a larger area while still getting all the items, and deduplicating at the end where the smaller circles interesect.

**Comment by Zip-creations** [comment]
The radius seems to work as intended, but the number of stores you get from one get_items() is limited by the page_size property as well. page_size is set to 20 by default. You can increase that by simply putting client.get_items(page_size=number)
