### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by maximilianpazze** [ahivert/tgtg-python#234]
Hi to you all,

I get the following API Error:  

TgtgAPIError: (400, b'{"errors":[{"code":"VALIDATION_ERROR","message":"JSON parse error: java.lang.reflect.InvocationTargetException; nested exception is com.fasterxml.jackson.databind.JsonMappingException: java.lang.reflect.InvocationTargetException (through reference chain: dk.tgtg.ike.api.mobile.item.model.MobileListItemRequest[\\"user_id\\"])"}]}')

I'm relatively new to coding, so a tip in which direction i can go to resolve this issue would be greatly appreciated :)

**Comment by ahivert** [comment]
In order to help you, can you attach the code you are trying to run ?

Le mer. 26 avr. 2023, 13:06, maximilianpazze ***@***.***> a
écrit :

**Comment by ahivert** [comment]
user_id **must not** be wrapped into `<>`

**Comment by maximilianpazze** [comment]
ah, stupid beginners mistake :) Thank you a lot for the help
