### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by antonioli86** [ahivert/tgtg-python#245]
Hi,
It seems the issue with captcha returned. Anyone noticed?

**Comment by Der-Henning** [comment]
Hi.
The API endpoint `item/v7/` seems to have stopped working. `item/v8/` seems to be the new endpoint and seems to work the same way as the old one.

**Comment by antonioli86** [comment]
Its seems API endpoint update does the job. Thanks @Der-Henning .

**Comment by ahivert** [comment]
version 0.16.0 has been published. That was a fast one ! thanks again @Der-Henning

**Comment by Der-Henning** [comment]
@ahivert
I cannot see any changes in the behavior of the `v8` endpoint but we should do some research on it. Maybe TGTG only made some changes in the backend.
