### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by matheohan** [ahivert/tgtg-python#247]
Hey,

First of all thank you for this awesome API wrapper.

I have the following error since _25/05_.
### **Error**: 
`TgtgAPIError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAWuR8sMjLg8MAdMt_fA==&cid=7Wq6KBvRdcdRzk~b5AzEpYvzNwR-NRIwsSHL0fXoz96Hta-rB1Gf5_GwM5-xsKUMLkDwc7HKhURONDETU3KWUHXVFL7bB2Xy9pmlHeNk1SAZj3R9j3wVFxKPU~Iyg0Rd&referer=https%3A%2F%2Fapptoogoodtogo.com%2Fapi%2Fauth%2Fv3%2FsignUpByEmail&hash=1D42C2CA6131C526E09F294FE96F94&t=fe&s=43513&e=a766b1f9906a156a96c31ea2ee14747f336897781abe3801ccfe1b2b82d4a6c0"}')`

### **What i've tried**: 
solve the captcha with the link or directly on the tgtg app (i got the captcha on the app)

### **Info**: 
Im running this api on a vps (maybe this imply that i can't solve the captcha ? / to note: whether i use vpn to solve the captcha or not it doesn't works) 
Moreover, the error occurs whenever i want to use client.get_credentials() after initializing client with client.signup_by_email method or TgtgClient.

Thanks in advance!

**Comment by KreCi-NET** [comment]
I had same problem since last 3 days. Upgrading from 0.14.0 to 0.16.0 and reauthorization has helped. Working again now.

**Comment by DIKINGVFX** [comment]
> I had same problem since last 3 days. Upgrading from 0.14.0 to 0.16.0 and reauthorization has helped. Working again now.

Hi, can you clarify what you mean by reauthorization ?
As for the version I'm currently on 0.16.0 so i don't know if it is related to that.

Thanks for you help!

**Comment by KreCi-NET** [comment]
> > I had same problem since last 3 days. Upgrading from 0.14.0 to 0.16.0 and reauthorization has helped. Working again now.
> 
> Hi, can you clarify what you mean by reauthorization ? As for the version I'm currently on 0.16.0 so i don't know if it is related to that.
> 
> Thanks for you help!

Clear the auth cookie.

**Comment by DIKINGVFX** [comment]
> > > I had same problem since last 3 days. Upgrading from 0.14.0 to 0.16.0 and reauthorization has helped. Working again now.
> > 
> > 
> > Hi, can you clarify what you mean by reauthorization ? As for the version I'm currently on 0.16.0 so i don't know if it is related to that.
> > Thanks for you help!
> 
> Clear the auth cookie.

Im sorry again but im unsure what is clear the auth cookie ? Can you explain in details how to do it ? 
What im trying to do here is : 

```
client = TgtgClient(email="myemail")
credentials = client.get_credentials()  <--- here occurs the 403 error
```

Thanks in advance and sorry for my ignorance.

**Comment by Rx2s1987** [comment]
I copied the Files from the Zip Folder in Directory tgtg to the TGTG File Directory in my System to upgrade it. pip uninstall tgtg and pip install tgtg was not working for me.

I have the problem that on my raspberry pi 4 tgtg gives me 403 but on my windows PC with cygwin it works perfectly. Booth systems has the same IP.

**Comment by DIKINGVFX** [comment]
UPDATE: 

Using the api with python3 on my vps do not work but using the same .py on jupyter notebook (also on my vps) works flawlessly.
If anyone have any clue ?

**Comment by jotjern** [comment]
I'm also having this issue.

**Comment by eggerand13** [comment]
Works fine on a Windows machine but fails with the error mentioned above on a Debian VPS.

**Comment by truongvinht** [comment]
It seems I figured out the issue.... Datadome is used for bot usage prevention. After changing IP address it works. Make sure to prevent being banned or blacklisted by reducing number of request or by spoofing different user agents

**Comment by TanguyOrtegat** [comment]
same issue on debian VPS. I am requesting each minute but been banned with my ip i think. 
tried to solve captcha on my computer but website says i have been banned.
Will try to use different useragent will let you know. 
Installing version 0.16 and having new coockies doesn't change anything

**Comment by Aimane-Anass** [comment]
I have the same issue. Any solution here ?

**Comment by jjmwiwi** [comment]
I have the same issue here Any solutions?
