### ISSUE TITLE
Retrieve Tokens - Cookie Missing

### ISSUE THREAD

**Issue by jdbuta** [ahivert/tgtg-python#248]
When I try to retrieve my tokens, following email authorization, all my tokens are printed except for the cookie. Any ideas why I can't retrieve this?

**Comment by H8mut** [comment]
> When I try to retrieve my tokens, following email authorization, all my tokens are printed except for the cookie. Any ideas why I can't retrieve this?

I have the same issue. On my Macbook everything works fine but on raspberry pi I have the issue.

**Comment by ahivert** [comment]
Do you use the last version available on pypi ?

Can you put here the output of `pip freeze` ?

**Comment by H8mut** [comment]
> Do you use the last version available on pypi ? Can you put here the output of `pip freeze` ? Le mer. 21 juin 2023, 08:38, H8mut ***@***.***> a écrit :
> […](#)

Thank you for your super fast response :) you brought me on the right track. Unfortunately my python version on the raspberry pi was old, so only a tgtg version of 0.13 something was available. I started the updating process of python and will report afterwards if everything works :) thanks again, great work here :)
