### ISSUE TITLE
Pay for reserved order

### ISSUE THREAD

**Issue by Oper18** [ahivert/tgtg-python#251]
I think that I doing something wrong but after I reserve order I can't pay it from my app, I see it as sold

**Comment by Oper18** [comment]
So, there is no way to make an order?
I mean that most of orders I reserve and pay in 5 minutes. But I can't pay reserved order, so now it could used only for playing not for get real orders?

**Comment by peterschwps** [comment]
@Oper18 not with this script. But check the oldest opened issue on here, someone made a fork and added the option to check out
