### ISSUE TITLE
Confusing "Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)"

### ISSUE THREAD

**Issue by matkoniecz** [ahivert/tgtg-python#261]
What is the supposed difference here? Why PC mailbox and mailbox on mobile would differ if both access the same client?

It seems to be not about using it without app, https://www.toogoodtogo.com/ does seem to be app only.

Or should I register business account?

Should I temporarily uninstall app?

I have not got any email. I checked spam folder.

**Comment by ahivert** [comment]
If you open the link in the email from you smartphone where tgtg app is
installed, the app will open the link. If the app open the link it will not
validate the access.
You can try it.

Le sam. 2 sept. 2023, 07:25, Mateusz Konieczny ***@***.***> a
écrit :

**Comment by matkoniecz** [comment]
Oh, the problem is that no email arrived at all.
