### ISSUE TITLE
Function client.set_favorite doesn't work anymore

### ISSUE THREAD

**Issue by NoRegrets06** [ahivert/tgtg-python#288]
Hello everyone,

the function `client.set_favorite(item_id=64346, is_favorite=True)` doesn't work anymore and returns a 404 error
-> `tgtg.exceptions.TgtgAPIError: (404, b'')`

maybe a different api endpoint ?
Thx for this amazing code ;)

**Comment by floriegl** [comment]
Did some Android MITM. The new Endpoint is POST /api/user/favorite/v1/{item_id}/update with body {"is_favorite":true} or {"is_favorite":false}
