### ISSUE TITLE
Missing api to get delivrable package

### ISSUE THREAD

**Issue by chauve-dev** [ahivert/tgtg-python#297]
Hi ! Is there any way to get delivrable package via the api ?

**Comment by MaxWinterstein** [comment]
What do you exactly mean? 

Sounds like https://github.com/ahivert/tgtg-python/issues/308 but that would lead to some time travel issues...

**Comment by chauve-dev** [comment]
Hi yes it's seems like that's what i'm talking about, in france we had access to that since 1 or 2 years
