### ISSUE TITLE
API v3 seems to be broken

### ISSUE THREAD

**Issue by edwinvanderham** [ahivert/tgtg-python#325]
As of today, I found myself confronted with the following exception when trying to login:

```
TgtgLoginError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/authByEmail.","instance":"/api/auth/v3/authByEmail"}')
```

When I use a browser to open the url https://apptoogoodtogo.com/api/auth/v3/authByEmail I indeed sse the same 404 not found.
Very interestingly, when I open the https://apptoogoodtogo.com/api/auth/v4/authByEmail I get a 405 instead.

It looks like the v3 api has been deprecated and replaced with v4

**Comment by ahivert** [comment]
can you try this PR ? https://github.com/ahivert/tgtg-python/pull/324

**Comment by ahivert** [comment]
release 0.18.0 published
