### ISSUE TITLE
Auth api not working

### ISSUE THREAD

**Issue by larkaa** [ahivert/tgtg-python#39]
Looks like 'auth/v1/loginByEmail' either stopped working or is down temporarily. Getting 403 responses.

**Comment by ahivert** [comment]
Thanks for using tgtg-python :)

Just tested on the app, endpoint  used is the same one that the lib use `/api/auth/v1/loginByEmail`.

Tested with the lib:
```
TgtgClient(email="<tgtg_email_account>", password="<tgtg_password_account>").get_items()
```
return my favourites so looks like you are trying to login with bad credentials  :thinking:

**Comment by larkaa** [comment]
Strange, trying to reset a password leads to a page with a 403 error as well. I guess it's not related to the code. Regional issue?
