### ISSUE TITLE
store_id

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [ahivert/tgtg-python#61]
Hi, notice that some stores have a alfanumeric character :

example 
![image](https://user-images.githubusercontent.com/70637347/101171384-f5d2bb00-363f-11eb-8962-7e8d51955dcd.png)

but the get_item() does not seem to accept this
Am I missing something?

**Comment by ahivert** [comment]
Hi,

The id that should be passed to `get_item()` is not the `store_id` but `ìtem_id`.

**Comment by Brolmeel** [comment]
nice that seems to work.
are there any examples available on how to work with the returned result list? Example get name of all store with available items.

**Comment by ahivert** [comment]
Not yet, but easy to loop over the list and print each item to see how the data is structured. Don't hesitate to open a PR to add that to the readme.

**Comment by Brolmeel** [comment]
to bad my python is not that good

**Comment by ahivert** [comment]
I have updated the readme with more information about results returned by get_item and get_items. Tell me if you need more.
