### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by FlyCodeine** [ahivert/tgtg-python#63]
I coded a monitor that checks every 10 seconds if a store in my area restocks.
After some time I run the script, i get a 401, unauthorized, so i'm guessing the token / auth expires.
Is there a way to renew it, without checking if i get the error code and inizializing the client every time?
Thanks.

**Comment by ahivert** [comment]
The lib could done that automatically yes.
On my side I instantiate the client every time I need to get some information. That's ugly :disappointed:
Could you provide more information about the exact response you received? Do you know the validity period of the token?

**Comment by Thorgal-The-Viking** [comment]
I have same issue. This is the response.


get_items
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (401, b'{"timestamp":1607702377148,"status":401,"error":"Unauthorized","message":"Unauthorized","path":"/api/item/v7/"}')

**Comment by ahivert** [comment]
Fixed in release 0.4.0
