### ISSUE TITLE
How to retreive access token 

### ISSUE THREAD

**Issue by stefanvangastel** [ahivert/tgtg-python#68]
It seems the `access_token` property is not set on the client object. 

This is causing the user to receive a login email every time the script runs.

**Comment by ahivert** [comment]
Are you using the last release published today, 0.4.0?

Doing something like this should work
```python
from tgtg import TgtgClient

client = TgtgClient(email=<email>, password=<password>)

# first time, it will log in using email and password
client.get_items()

# second time, it will use access token
client.get_items()
```
