### ISSUE TITLE
Remove store / items limit

### ISSUE THREAD

**Issue by FlyCodeine** [ahivert/tgtg-python#70]
I'm trying to get items in Milan, but looks like the answer i get is cut / limited in some way.
In the map i see about 200+ stores, while i'm only getting about 15/20 from the api.
Is there a way to get them all?

```
items = client.get_items(
    favorites_only=False,
    latitude=45.464820,
    longitude=9.188356,
    radius=30,
)
```

**Comment by ahivert** [comment]
You can get all params accepted by get_items [here](https://github.com/ahivert/tgtg-python/blob/master/tgtg/__init__.py#L123)

For your need, you have to call `get_items` with `page_size` options:
```python
items = client.get_items(
    favorites_only=False,
    latitude=45.464820,
    longitude=9.188356,
    radius=30,
    page_size=200,
)
```
